scrape_configs:
  - job_name: 'prometheus'
    static_configs: [{ targets: ['localhost:9090'] }]

  - job_name: 'sdn-backend'
    static_configs: [{ targets: ['sdn-backend:4000'] }]

  - job_name: 'opa'
    static_configs: [{ targets: ['opa:8181'] }]

  - job_name: 'sdn-oauth2-proxy'
    metrics_path: /metrics
    static_configs: [{ targets: ['sdn-oauth2-proxy:4180'] }]

  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs: [{ targets: ['grafana:3000'] }]
